refactoring and new tests
vdorofeev1/lottery pull request #2
Opened 2024-02-09 16:40 UTC by vdorofeev1

2024-02-12 04:09 UTC, bas-kirill requested changes
Не хватает:

1. .dockerignore (чтобы при изменении каких-то левых файлов не ребилдить постоянно образ)
2. Коллекция Postman
3. Нейминг ветки не по git flow: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
Еще есть другие стратегии ветвления: trunk-based и GitHub Flow. Посмотри про каждый, но ветки обычно именуют в стиле git flow, даже если это trunk-based
4. Нужен скрипт с пушом докер образа в Docker Hub
5. CI для прогонки тестов в контейнерах гитхаба
6. Переехать с embedded БД на PostgreSQL + добавить миграции на liquibase
7. Комиты по прежнему не в стиле. Я обычно именую так: `FIRE-AND-SWORD-143: ♻️ code review`: `название тикета: <смайлик из gitmoji.dev> <текст сообщения>`
8. `stop.sh` скрипт чтобы остановить сервис

2024-02-12 04:09 UTC, bas-kirill commented on src/main/java/org/example/lottery/exceptions/ParticipantNotFound.java
> +public class ParticipantNotFound extends RuntimeException {
Тут тоже, должно быть так:
```java
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
public class ParticipantNotFound extends RuntimeException {
```

2024-02-12 04:09 UTC, bas-kirill commented on src/main/java/org/example/lottery/exceptions/ParticipantNotFound.java
> +    }
Давай заюзаем форматированные строки?

`super("Participant with id=`%d` not found!".formatted(id));`

2024-02-12 04:09 UTC, bas-kirill commented on src/test/java/org/example/lottery/LotteryApplicationTests.java
Все супер, давай назовем тест как интеграционный: `LotteryServiceIntegrationTest.java` (можно по-другому, главное чтобы суфикс был на `*IntegrationTest.java` + добавим юнит-тестов? 🙂

2024-02-12 04:19 UTC, bas-kirill commented
Добавь в `readme.md`, чтобы не выглядело совсем сухо 🙂 
![image](https://github.com/vdorofeev1/lottery/assets/39113667/f18174ff-d498-4619-b3fb-1549672c0945)

2024-02-16 08:59 UTC, bas-kirill commented on scripts/run.sh
> +java -jar target/${NAME}-${VERSION}.jar
Я бы так сделал (чуть поменяй под себя:
```bash
set -e
currentDir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
rootDir="$currentDir/../../"

(cd "$rootDir" && exec ./buildDockerImage.sh
```

2024-02-16 08:59 UTC, bas-kirill commented on scripts/upkg.json
Впервые вижу, это же сам придумал или где-то было предложение сделать конфигурация jar как в сборках для жса?

2024-02-16 08:59 UTC, bas-kirill commented on src/main/java/org/example/lottery/controllers/LotteryController.java
>      }
Давай сделаем отдельные модельки для контроллера (view-модельки) и для сервисного уровня, чтобы не смешивать?

2024-03-05 10:07 UTC, bas-kirill commented
@vdorofeev1 Валя, СРОЧНО! Сроки ГОРЯТ, нужно закрыть PR с учетом замечаний как МОЖНО СКОРЕЕ!

2024-03-05 10:10 UTC, vdorofeev1 commented
Кирилл, у меня жена РОЖАЕТ!!!!

2024-03-20 12:14 UTC, merged